repository: xsaori/xsaori.github.io
theme: jekyll-theme-slate
#theme: jekyll-theme-cayman
#theme: jekyll-theme-minimal

title: Welcome to Saori Tanaka's Pages
description:  

#github:
#  is_project_page: false